import pandas as pd
data = {'Student_ID': [101, 102, 103, 104, 105],'Name': ['karthik', 'akhil', 'chandu', 'surya', 'prahalad'],'Python_Marks': [78, 85, 67, 90, 88]}
df = pd.DataFrame(data)
print("Original DataFrame:\n")
print(df)
sorted_df = df.sort_values(by='Python_Marks')
print("Sorted by Python_Marks (Ascending):")
print(sorted_df)
sorted_desc = df.sort_values(by='Python_Marks', ascending=False)
print("Sorted by Python_Marks (Descending):")
print(sorted_desc)
print("First 3 rows:")
print(df[:3])
print("Rows from index 1 to 3:")
print(df.iloc[1:4])
print("Only Name and Python_Marks columns:")
print(df[['Name', 'Python_Marks']])
print("Rows 1 to 3 and selected columns:")
print(df.loc[1:3, ['Name', 'Python_Marks']])